### ISSUE TITLE
Latest release not published?

### ISSUE THREAD

**Issue by eric-swann-q2** [MindscapeHQ/ember-cli-raygun#12] opened 2017-03-17 21:51 UTC
Hey guys, I see that you've dropped a recent release here but it's not published to NPM.  Is this by design?

**Comment by pixelhandler** [comment] 2017-03-17 22:38
@eric-swann-q2 I also opened an issue #11

**Comment by nikz** [comment] 2017-03-18 03:54
Duplicate of #11

**Closed** 2017-03-19 18:07 UTC
